language: objective-c
osx_image: xcode7.3
cache: cocoapods
notifications:
  email: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Quaderno.xcworkspace
  - SCHEME=Quaderno
  - DESTINATION="OS=9.3,name=iPhone 5S"
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
install:
  - pod install
script:
  - set -o pipefail

  - xcodebuild -version
  - xcodebuild -showsdks

  # Run tests in Debug
  - xcodebuild -workspace "${WORKSPACE}" -scheme "${SCHEME}" -destination "${DESTINATION}" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

  # Run tests in Release
  - xcodebuild -workspace "${WORKSPACE}" -scheme "${SCHEME}" -destination "${DESTINATION}" -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c

  # Check CocoaPods specs
  - pod lib lint --quick # This must be quick due to a warning in Alamofire
