language: objective-c
osx_image: xcode8.2
notifications:
  email: false
before_install:
  - bundle install
  - bundle exec pod repo update
env:
  matrix:
    - DESTINATION="OS=9.0,name=iPhone 6"
    - DESTINATION="OS=10.0,name=iPhone 6s Plus"
script:
  - set -o pipefail
  - xcodebuild -destination "${DESTINATION}" -sdk iphonesimulator10.2 -workspace Quaderno.xcworkspace -scheme Quaderno -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES clean build test | xcpretty
